### ISSUE TITLE
我看到你用到了docker, 那么uikit它们俩是不是同类型产品?

### ISSUE THREAD

**Issue by tidys** [tickbh/VisualUIEditor#2]
以前没做过前端,不是太了解这么框架啥的,我想知道docker,uikit是不是都是第三方控件框架,不知道我这么理解正确不?你当初选择docker的原因是啥?还有vue是干啥的?

**Comment by tidys** [comment]
好吧,原谅我问这么幼稚的问题,是wcDocker,不是Docker
当时你是怎么找到这个第三方库的?

**Comment by tickbh** [comment]
本来是用另一个框架的, 但是那个框架有版权问题, 就改成这个了.. google
